# Generated by Django 5.2.5 on 2025-08-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="tags",
            field=models.ManyToManyField(blank=True, to="users.tag"),
        ),
    ]
