# Generated by Django 5.2.5 on 2025-08-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_lesson_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a cover image for this course.",
                null=True,
                upload_to="lesson_covers/",
            ),
        ),
    ]
