# Generated by Django 5.2.5 on 2025-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_lesson_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="e.g., Professor of Computer Science",
                max_length=200,
            ),
        ),
    ]
