# Generated by Django 5.2.5 on 2025-08-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_studio_job_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="social_links",
            field=models.JSONField(
                blank=True,
                help_text="e.g., {'email': 'teacher@example.com', 'linkedin': '...'}",
                null=True,
            ),
        ),
    ]
