# Generated by Django 5.2.5 on 2025-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_studio_social_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="degrees_text",
        ),
        migrations.AddField(
            model_name="studio",
            name="degrees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of degrees, e.g., ["B.Sc. Computer Science", "M.Sc. AI"]',
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="cv_file",
            field=models.FileField(blank=True, null=True, upload_to="cv_files/"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="experience",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of experiences, e.g., [{"title": "Software Engineer", "company": "Google"}]',
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="social_links",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
