# Generated by Django 5.2.5 on 2025-08-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_studio_degrees_text_studio_degrees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True, help_text="A short description of the course."
            ),
        ),
    ]
