# Generated by Django 5.2.5 on 2025-08-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_lesson_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
