# Generated by Django 5.2.5 on 2025-08-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_lesson_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_me",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="profile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
