# Generated by Django 5.2.5 on 2025-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_profile_about_me_profile_contact_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.AddField(
            model_name="profile",
            name="username_last_changed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
