# Generated by Django 5.2.5 on 2025-09-05 09:38

from django.db import migrations


def create_teacher_group(apps, schema_editor):
    """
    This function is run when we apply the migration.
    It finds or creates our "Teachers" group.
    """
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Teachers")


def remove_teacher_group(apps, schema_editor):
    """
    This function is run if we ever need to "un-apply" the migration.
    It safely removes the "Teachers" group.
    """
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Teachers").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_profile_bio_profile_username_last_changed"),
    ]

    operations = [
        migrations.RunPython(create_teacher_group, remove_teacher_group),
    ]
