# Generated by Django 5.2.5 on 2025-09-08 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_create_teacher_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studio",
            name="cv_file",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="degrees",
        ),
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(blank=True, null=True, upload_to="cv_files/"),
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="degree_files/")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="degrees",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
