# Generated by Django 5.2.5 on 2025-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_remove_studio_cv_file_remove_studio_degrees_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studio",
            name="cover_image",
            field=models.ImageField(
                default="studio_covers/default_cover.jpg", upload_to="studio_covers/"
            ),
        ),
    ]
