# Generated by Django 5.2.5 on 2025-09-13 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_alter_studio_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="degrees",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of degrees or certifications as a JSON list.",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="cv_files/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "txt"]
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Degree",
        ),
    ]
