# Generated by Django 5.2.5 on 2025-09-17 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_profile_degrees_alter_profile_cv_file_delete_degree"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="about_me",
            new_name="headline",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="studio",
            name="social_links",
        ),
        migrations.AddField(
            model_name="studio",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_studios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StudioRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "studio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="users.studio",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("studio", "user")},
            },
        ),
    ]
