# Generated by Django 5.2.5 on 2025-09-21 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_rename_about_me_profile_headline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="content",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="file_upload",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="order",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_upload",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="video_url",
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_file",
            field=models.FileField(
                blank=True,
                help_text="A downloadable file for the lesson.",
                null=True,
                upload_to="lesson_files/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown Text"),
                    ("file", "Downloadable File"),
                    ("video", "Single Video"),
                    ("playlist", "Video Playlist"),
                ],
                default="markdown",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_video",
            field=models.FileField(
                blank=True,
                help_text="A single video file for the lesson.",
                null=True,
                upload_to="lesson_videos/",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="markdown_content",
            field=models.TextField(
                blank=True, help_text="Content for markdown-based lessons.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_covers/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="PlaylistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="playlist_videos/")),
                ("order", models.PositiveIntegerField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playlist_items",
                        to="users.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
