# Generated by Django 5.2.5 on 2025-09-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_lesson_content_remove_lesson_file_upload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("markdown", "Markdown Text"),
                    ("file", "Downloadable File"),
                    ("video", "Single Video"),
                ],
                default="markdown",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="PlaylistItem",
        ),
    ]
