# Generated by Django 5.2.5 on 2025-09-25 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_alter_lesson_lesson_type_delete_playlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="studio",
            name="cover_image",
            field=models.ImageField(
                default="studio_covers/default_studio_cover.jpg",
                upload_to="studio_covers/",
            ),
        ),
    ]
