# Generated by Django 5.2.5 on 2025-09-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="studio",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="studio_covers/"),
        ),
    ]
