# Generated by Django 5.2.5 on 2025-09-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_profile_profile_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="file_attachment",
            field=models.FileField(
                blank=True, null=True, upload_to="post_attachments/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(blank=True, to="users.tag"),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled Post", max_length=255),
        ),
    ]
